---
http_interactions:
- request:
    method: post
    uri: http://123:abc@localhost:3003/oauth/token
    body:
      encoding: US-ASCII
      string: grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - ! '*/*'
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Cache-Control:
      - no-store
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"030ffc34c73241d72d05aca483ddd03f"
      X-Request-Id:
      - f9eeabfc-3bbc-4194-9f5e-5933e57c1220
      X-Runtime:
      - '0.015146'
      Connection:
      - close
      Server:
      - thin
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"42ad7558a7079e5ffe21572066a090693e5da796fcd64c762ef24c74de196f82","token_type":"bearer"}'
    http_version: 
  recorded_at: Mon, 12 Jan 2015 21:08:51 GMT
recorded_with: VCR 2.9.3
