---
http_interactions:
- request:
    method: post
    uri: http://123:abc@localhost:3003/oauth/token
    body:
      encoding: US-ASCII
      string: grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/x-www-form-urlencoded
      Accept:
      - ! '*/*'
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Cache-Control:
      - no-store
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"0ca465e9d10227536649a9a792cc54db"
      X-Request-Id:
      - b36101f4-d20d-4252-984e-9d05e407b964
      X-Runtime:
      - '0.038247'
      Connection:
      - close
      Server:
      - thin
    body:
      encoding: US-ASCII
      string: ! '{"access_token":"979ac610d4da56843c76250ffe2a33a7a1324d54c12c3b6a06f2ef5a0cc53588","token_type":"bearer"}'
    http_version: 
  recorded_at: Mon, 12 Jan 2015 20:14:54 GMT
recorded_with: VCR 2.9.3
